# Generated by Django 4.2.1 on 2023-06-04 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_features'),
        ('contacts', '0002_alter_contact_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cars',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
            preserve_default=False,
        ),
    ]
