# Generated by Django 4.2.1 on 2023-05-22 18:04

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=260)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina')], max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='year')),
                ('condition', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('car_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('car_image_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_image_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_image_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_image_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Bluetooth Connectivity', 'Bluetooth Connectivity'), ('Backup Camera', 'Backup Camera'), ('Navigation System', 'Navigation System'), ('Keyless Entry', 'Keyless Entry'), ('Leather Seats', 'Leather Seats'), ('Heated Seats', 'Heated Seats'), ('Sunroof/Moonroof', 'Sunroof/Moonroof'), ('Parking Sensors', 'Parking Sensors'), ('Emergency Braking', 'Emergency Braking'), ('Apple CarPlay', 'Apple CarPlay'), ('Android Auto', 'Android Auto'), ('Wireless Charging', 'Wireless Charging'), ('Dual-zone Climate Control', 'Dual-zone Climate Control'), ('USB Ports', 'USB Ports')], max_length=258)),
                ('body_style', models.CharField(max_length=300)),
                ('engine', models.CharField(max_length=300)),
                ('transmission', models.CharField(max_length=300)),
                ('interior', models.CharField(max_length=300)),
                ('miles', models.IntegerField()),
                ('doors', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=300)),
                ('passengers', models.IntegerField()),
                ('vin_no', models.CharField(max_length=300)),
                ('miliage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=300)),
                ('no_of_owners', models.CharField(max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
